/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupIdIndexRouteImport } from './routes/group/$id/index'
import { Route as GroupIdWorkflowIdRouteImport } from './routes/group/$id/$workflowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdIndexRoute = GroupIdIndexRouteImport.update({
  id: '/group/$id/',
  path: '/group/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdWorkflowIdRoute = GroupIdWorkflowIdRouteImport.update({
  id: '/group/$id/$workflowId',
  path: '/group/$id/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/group/$id/$workflowId': typeof GroupIdWorkflowIdRoute
  '/group/$id/': typeof GroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/group/$id/$workflowId': typeof GroupIdWorkflowIdRoute
  '/group/$id': typeof GroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/group/$id/$workflowId': typeof GroupIdWorkflowIdRoute
  '/group/$id/': typeof GroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/group/$id/$workflowId' | '/group/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/group/$id/$workflowId' | '/group/$id'
  id: '__root__' | '/' | '/group/$id/$workflowId' | '/group/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupIdWorkflowIdRoute: typeof GroupIdWorkflowIdRoute
  GroupIdIndexRoute: typeof GroupIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/': {
      id: '/group/$id/'
      path: '/group/$id'
      fullPath: '/group/$id/'
      preLoaderRoute: typeof GroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/$workflowId': {
      id: '/group/$id/$workflowId'
      path: '/group/$id/$workflowId'
      fullPath: '/group/$id/$workflowId'
      preLoaderRoute: typeof GroupIdWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupIdWorkflowIdRoute: GroupIdWorkflowIdRoute,
  GroupIdIndexRoute: GroupIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
