// Auto-generated by fnrpc. DO NOT EDIT.
// This file has been generated by Specta. Do not edit this file manually.
/**
 *  字幕对齐位置 (镜像 TS `packages/core/stages/mix_video/args.ts` alignmentList)
 * 
 *  顺序即 ffmpeg ass `Alignment` 数值 (1..9), 见 [`alignment_to_ffmpeg`]。
 */
export type Alignment = "bottom-left" | "bottom-center" | "bottom-right" | "middle-left" | "center" | "middle-right" | "top-left" | "top-center" | "top-right";

/**  asr 阶段参数。 */
export type AsrArgs = AsrArgs_Serialize | AsrArgs_Deserialize;

/**  asr 阶段参数。 */
export type AsrArgs_Deserialize = {
	/**  推理运行时, 默认 pytorch */
	runtime?: AsrRuntime,
	/**  推理设备, 默认 cuda */
	device?: AsrDevice,
	/**  使用分离后的人声 (target_3_vocals.wav) 而非原始视频音频 */
	useSeparated?: boolean,
	/**  是否启用本阶段 (缺省 true; 设为 false 可跳过 asr, 与 translate.enabled 一致) */
	enabled?: boolean,
	/**  ASR 音频源 (默认 sidechain) */
	mixMode?: MixMode,
	/**  背景音降低量(dB); raw-sum 叠加前衰减, sidechain 时压缩后额外衰减; 默认 -12 */
	reduceBgm?: number | null,
	/**  是否在 asr.json 中包含词级时间戳 (words), 分离场景下可能受幻觉影响; 默认关闭, 调试时开启 */
	wordsOutput?: boolean,
	/**  mixMode=sidechain 时侧链压缩器参数 */
	sidechainCompress?: SidechainCompress_Deserialize,
	/**  对分离后的人声应用 silence gate 过滤静音段噪声 */
	useGate?: boolean,
	/**  ASR 输入的人声音频路径, 调试使用 */
	vocalAudioPath?: string | null,
	/**  whisper.cpp: 启用 VAD */
	vad?: boolean,
	/**  whisper.cpp: VAD 模型, silero-v5 (默认) 或 silero-v6 */
	vadModel?: VadModel | null,
	/**  whisper.cpp: VAD 阈值, 默认 0.5 */
	vadThreshold?: number | null,
	/**  whisper.cpp: no-speech 阈值, 默认 0.6 */
	noSpeechThold?: number | null,
	/**  whisper.cpp: 解码温度, 默认 0.0 */
	temperature?: number | null,
	/**  whisper.cpp: 最大段长(字符), 0=不限 */
	maxLen?: number,
	/**  whisper.cpp: 按词边界分割 */
	splitOnWord?: boolean,
};

/**  asr 阶段参数。 */
export type AsrArgs_Serialize = {
	/**  推理运行时, 默认 pytorch */
	runtime: AsrRuntime,
	/**  推理设备, 默认 cuda */
	device: AsrDevice,
	/**  使用分离后的人声 (target_3_vocals.wav) 而非原始视频音频 */
	useSeparated: boolean,
	/**  是否启用本阶段 (缺省 true; 设为 false 可跳过 asr, 与 translate.enabled 一致) */
	enabled: boolean,
	/**  ASR 音频源 (默认 sidechain) */
	mixMode: MixMode,
	/**  背景音降低量(dB); raw-sum 叠加前衰减, sidechain 时压缩后额外衰减; 默认 -12 */
	reduceBgm: number | null,
	/**  是否在 asr.json 中包含词级时间戳 (words), 分离场景下可能受幻觉影响; 默认关闭, 调试时开启 */
	wordsOutput: boolean,
	/**  mixMode=sidechain 时侧链压缩器参数 */
	sidechainCompress: SidechainCompress_Serialize,
	/**  对分离后的人声应用 silence gate 过滤静音段噪声 */
	useGate: boolean,
	/**  ASR 输入的人声音频路径, 调试使用 */
	vocalAudioPath: string | null,
	/**  whisper.cpp: 启用 VAD */
	vad: boolean,
	/**  whisper.cpp: VAD 模型, silero-v5 (默认) 或 silero-v6 */
	vadModel: VadModel | null,
	/**  whisper.cpp: VAD 阈值, 默认 0.5 */
	vadThreshold: number | null,
	/**  whisper.cpp: no-speech 阈值, 默认 0.6 */
	noSpeechThold: number | null,
	/**  whisper.cpp: 解码温度, 默认 0.0 */
	temperature: number | null,
	/**  whisper.cpp: 最大段长(字符), 0=不限 */
	maxLen: number,
	/**  whisper.cpp: 按词边界分割 */
	splitOnWord: boolean,
};

/**  推理设备 (asr 侧无 webgpu)。 */
export type AsrDevice = "vulkan" | "cuda" | "cpu" | "mps";

/**  asr 阶段修正参数。 */
export type AsrFixArgs = AsrFixArgs_Serialize | AsrFixArgs_Deserialize;

/**  asr 阶段修正参数。 */
export type AsrFixArgs_Deserialize = {
	/**  ASR 结果文件路径, 调试使用 */
	asrFilePath?: string | null,
	/**  是否启用本阶段 (缺省 true; 设为 false 可跳过 asr_fix) */
	enabled?: boolean,
} & LlmFixArgs_Deserialize;

/**  asr 阶段修正参数。 */
export type AsrFixArgs_Serialize = {
	/**  ASR 结果文件路径, 调试使用 */
	asrFilePath: string | null,
	/**  是否启用本阶段 (缺省 true; 设为 false 可跳过 asr_fix) */
	enabled: boolean,
} & LlmFixArgs_Serialize;

/**
 *  asr_ocr 阶段参数。
 * 
 *  注意: 父结构用 `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故手写
 *  `impl Default` 以保证默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type AsrOcrArgs = AsrOcrArgs_Serialize | AsrOcrArgs_Deserialize;

/**
 *  asr_ocr 阶段参数。
 * 
 *  注意: 父结构用 `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故手写
 *  `impl Default` 以保证默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type AsrOcrArgs_Deserialize = SfOcrArgs_Deserialize;

/**
 *  asr_ocr 阶段参数。
 * 
 *  注意: 父结构用 `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故手写
 *  `impl Default` 以保证默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type AsrOcrArgs_Serialize = SfOcrArgs_Serialize;

/**
 *  asr_ocr 阶段 OCR 修正参数。
 * 
 *  注意: 父结构用 `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故手写
 *  `impl Default` 以保证默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type AsrOcrFixArgs = AsrOcrFixArgs_Serialize | AsrOcrFixArgs_Deserialize;

/**
 *  asr_ocr 阶段 OCR 修正参数。
 * 
 *  注意: 父结构用 `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故手写
 *  `impl Default` 以保证默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type AsrOcrFixArgs_Deserialize = {
	/**  是否重采样 */
	isResample?: boolean,
} & OcrFixArgs_Deserialize;

/**
 *  asr_ocr 阶段 OCR 修正参数。
 * 
 *  注意: 父结构用 `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故手写
 *  `impl Default` 以保证默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type AsrOcrFixArgs_Serialize = {
	/**  是否重采样 */
	isResample: boolean,
} & OcrFixArgs_Serialize;

/**
 *  asr_ocr 阶段预处理参数。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type AsrOcrPreArgs = AsrOcrPreArgs_Serialize | AsrOcrPreArgs_Deserialize;

/**
 *  asr_ocr 阶段预处理参数。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type AsrOcrPreArgs_Deserialize = {
	/**  帧率 (fps), 越高时间戳越准但越慢; 默认 2 */
	fps?: number | null,
};

/**
 *  asr_ocr 阶段预处理参数。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type AsrOcrPreArgs_Serialize = {
	/**  帧率 (fps), 越高时间戳越准但越慢; 默认 2 */
	fps: number | null,
};

export type AsrRunInfo = AsrRunInfo_Serialize | AsrRunInfo_Deserialize;

export type AsrRunInfo_Deserialize = {
	engine: string,
	device: string,
	compute_type?: string | null,
	gpu_attempted?: boolean | null,
	fallback_to_cpu?: boolean | null,
};

export type AsrRunInfo_Serialize = {
	engine: string,
	device: string,
	compute_type: string | null,
	gpu_attempted: boolean | null,
	fallback_to_cpu: boolean | null,
};

/**
 *  asr 推理运行时。
 * 
 *  TS 侧为 `z.enum(["ggml", "faster-whisper", "pytorch"])` (kebab-case),
 *  故用 `rename_all = "kebab-case"` (`FasterWhisper` → `"faster-whisper"`)。
 */
export type AsrRuntime = "ggml" | "faster-whisper" | "pytorch";

export type Capabilities = {
	webgpu: boolean,
	vulkan: boolean,
	cuda: boolean,
	rocm: boolean,
	directml: boolean,
	mps: boolean,
	openvino: boolean,
};

/**  命令 */
export type Command = "task" | "env" | "servers" | "cookie" | "check" | "deviceinfo" | "listmodels";

/**  cookie 动作 */
export type CookieAction = "set";

/**  cookie 命令参数 (镜像 TS `CookieArgsSchema`: action=set + service=youtube + content 可选)。 */
export type CookieArgs = CookieArgs_Serialize | CookieArgs_Deserialize;

/**  cookie 命令参数 (镜像 TS `CookieArgsSchema`: action=set + service=youtube + content 可选)。 */
export type CookieArgs_Deserialize = {
	/**  动作: set (当前仅支持) */
	action?: CookieAction,
	/**  服务: youtube (当前仅支持) */
	service?: CookieService,
	/**  Netscape cookie 内容; 为空则从 stdin 读取 */
	content?: string | null,
};

/**  cookie 命令参数 (镜像 TS `CookieArgsSchema`: action=set + service=youtube + content 可选)。 */
export type CookieArgs_Serialize = {
	/**  动作: set (当前仅支持) */
	action: CookieAction,
	/**  服务: youtube (当前仅支持) */
	service: CookieService,
	/**  Netscape cookie 内容; 为空则从 stdin 读取 */
	content: string | null,
};

/**  cookie 所属服务 */
export type CookieService = "youtube";

export type CpuInfo = {
	model: string,
	cores: number,
	speedMHz: number | null,
};

/**  推理设备 */
export type Device = "vulkan" | "webgpu" | "cuda" | "cpu" | "mps";

export type DeviceInfo = DeviceInfo_Serialize | DeviceInfo_Deserialize;

export type DeviceInfo_Deserialize = {
	platform: PlatformInfo_Deserialize,
	cpu: CpuInfo,
	memory: MemoryInfo,
	gpu: GpuInfo_Deserialize[],
	ort: OrtInfo,
};

export type DeviceInfo_Serialize = {
	platform: PlatformInfo_Serialize,
	cpu: CpuInfo,
	memory: MemoryInfo,
	gpu: GpuInfo_Serialize[],
	ort: OrtInfo,
};

export type DirEntry = DirEntry_Serialize | DirEntry_Deserialize;

export type DirEntry_Deserialize = {
	name: string,
	is_dir: boolean,
	size?: bigint | null,
};

export type DirEntry_Serialize = {
	name: string,
	is_dir: boolean,
	size: bigint | null,
};

/**  env 动作 (也用于 clap `--action` 命令行解析) */
export type EnvAction = "check" | "ensure";

/**
 *  `env` 命令参数。
 * 
 *  `action` 决定 check / ensure; `targets` 指定要检查的环境项 key (空 → 按 stages 配置推断)。
 */
export type EnvArgs = EnvArgs_Serialize | EnvArgs_Deserialize;

/**
 *  `env` 命令参数。
 * 
 *  `action` 决定 check / ensure; `targets` 指定要检查的环境项 key (空 → 按 stages 配置推断)。
 */
export type EnvArgs_Deserialize = {
	/**  动作: check (默认) / ensure */
	action?: EnvAction,
	/**  要检查/ensure 的环境项; 空数组 → 按 input.jsonc 的 stages 配置推断所需项 */
	targets?: string[],
};

/**
 *  `env` 命令参数。
 * 
 *  `action` 决定 check / ensure; `targets` 指定要检查的环境项 key (空 → 按 stages 配置推断)。
 */
export type EnvArgs_Serialize = {
	/**  动作: check (默认) / ensure */
	action: EnvAction,
	/**  要检查/ensure 的环境项; 空数组 → 按 input.jsonc 的 stages 配置推断所需项 */
	targets: string[],
};

export type FoundVia = "Mdns" | "Default" | "PortFile";

export type FrameRate = {
	numerator: number,
	denominator: number,
};

export type GpuInfo = GpuInfo_Serialize | GpuInfo_Deserialize;

export type GpuInfo_Deserialize = {
	name: string,
	vendor: Vendor,
	architecture?: string | null,
	driverVersion: string,
	temperature: number | null,
	gpuPercent: number | null,
	gfxVersion?: string | null,
	vram: VramInfo_Deserialize,
	capabilities: Capabilities,
	hsaOverrideGfx?: string | null,
	vulkanHeaps?: VulkanHeaps | null,
	opProbes?: OpProbes_Deserialize | null,
};

export type GpuInfo_Serialize = {
	name: string,
	vendor: Vendor,
	architecture?: string,
	driverVersion: string,
	temperature: number | null,
	gpuPercent: number | null,
	gfxVersion?: string,
	vram: VramInfo_Serialize,
	capabilities: Capabilities,
	hsaOverrideGfx?: string,
	vulkanHeaps?: VulkanHeaps,
	opProbes?: OpProbes_Serialize,
};

export type GroupInfo = GroupInfo_Serialize | GroupInfo_Deserialize;

export type GroupInfo_Deserialize = {
	group_id: string,
	task_count: number,
	created_at?: string | null,
	tasks: TaskBrief_Deserialize[],
};

export type GroupInfo_Serialize = {
	group_id: string,
	task_count: number,
	created_at: string | null,
	tasks: TaskBrief_Serialize[],
};

/**  顶层输入 */
export type Input = Input_Serialize | Input_Deserialize;

/**  顶层输入 */
export type Input_Deserialize = {
	/**  任务参数, 仅 command=task 时必须 */
	task?: TaskArgs_Deserialize | null,
	/**  执行命令 (默认 env) */
	command?: Command,
	/**  服务端参数 (镜像 servers/args.ts), 仅 command=servers 时使用 */
	servers?: ServersArgs_Deserialize | null,
	/**  env 命令参数 (镜像 env/input.ts); targets 为空时按 stages 配置推断所需环境项 */
	env?: EnvArgs_Deserialize | null,
	/**  cookie 命令参数 (镜像 cmd/cookie/args.ts), 仅 command=cookie 时使用 */
	cookie?: CookieArgs_Deserialize | null,
	stages?: Stages_Deserialize,
};

/**  顶层输入 */
export type Input_Serialize = {
	/**  任务参数, 仅 command=task 时必须 */
	task: TaskArgs_Serialize | null,
	/**  执行命令 (默认 env) */
	command: Command,
	/**  服务端参数 (镜像 servers/args.ts), 仅 command=servers 时使用 */
	servers: ServersArgs_Serialize | null,
	/**  env 命令参数 (镜像 env/input.ts); targets 为空时按 stages 配置推断所需环境项 */
	env: EnvArgs_Serialize | null,
	/**  cookie 命令参数 (镜像 cmd/cookie/args.ts), 仅 command=cookie 时使用 */
	cookie: CookieArgs_Serialize | null,
	stages: Stages_Serialize,
};

/**  LLM 修正参数。 */
export type LlmFixArgs = LlmFixArgs_Serialize | LlmFixArgs_Deserialize;

/**  LLM 修正参数。 */
export type LlmFixArgs_Deserialize = {
	/**  LLM 模型名 */
	llmModel?: string,
	/**  LLM API 地址 */
	llmApiBase?: string,
	/**  领域提示, 帮助 LLM 理解上下文，例如"仙侠题材，角色：叶白、慧天、夜白" */
	domainHint?: string | null,
	/**  是否启用 LLM 修正 */
	llmFix?: boolean,
};

/**  LLM 修正参数。 */
export type LlmFixArgs_Serialize = {
	/**  LLM 模型名 */
	llmModel: string,
	/**  LLM API 地址 */
	llmApiBase: string,
	/**  领域提示, 帮助 LLM 理解上下文，例如"仙侠题材，角色：叶白、慧天、夜白" */
	domainHint: string | null,
	/**  是否启用 LLM 修正 */
	llmFix: boolean,
};

export type MemoryInfo = {
	total: string,
	free: string,
	processHeapUsed: string,
};

/**
 *  mix_audio 阶段参数 (镜像 TS `packages/core/stages/mix_audio/args.ts` MixAudioArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type MixAudioArgs = MixAudioArgs_Serialize | MixAudioArgs_Deserialize;

/**
 *  mix_audio 阶段参数 (镜像 TS `packages/core/stages/mix_audio/args.ts` MixAudioArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type MixAudioArgs_Deserialize = {
	/**  TTS 音频最大变速比, 1.0=不变速; 默认 1.35 */
	maxSpeed?: number | null,
	/**  字幕允许提前显示的最大毫秒数, 利用前段剩余时间; 默认 500 */
	maxAdvanceMs?: number | null,
	/**  字幕允许延迟显示的最大毫秒数, 借用后段留白; 默认 500 */
	maxDelayMs?: number | null,
};

/**
 *  mix_audio 阶段参数 (镜像 TS `packages/core/stages/mix_audio/args.ts` MixAudioArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type MixAudioArgs_Serialize = {
	/**  TTS 音频最大变速比, 1.0=不变速; 默认 1.35 */
	maxSpeed: number | null,
	/**  字幕允许提前显示的最大毫秒数, 利用前段剩余时间; 默认 500 */
	maxAdvanceMs: number | null,
	/**  字幕允许延迟显示的最大毫秒数, 借用后段留白; 默认 500 */
	maxDelayMs: number | null,
};

/**  ASR 音频源: vocals=纯分离人声, raw-sum=直接叠加, sidechain=侧链压缩背景音 */
export type MixMode = "vocals" | "raw-sum" | "sidechain";

/**
 *  mix_video 阶段参数 (镜像 TS `packages/core/stages/mix_video/args.ts` MixVideoArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type MixVideoArgs = MixVideoArgs_Serialize | MixVideoArgs_Deserialize;

/**
 *  mix_video 阶段参数 (镜像 TS `packages/core/stages/mix_video/args.ts` MixVideoArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type MixVideoArgs_Deserialize = {
	/**
	 *  字幕字号, 不填则自动: 竖屏 12(zh)/9(其他) ← 横屏 24(zh)/18(其他)
	 * 
	 *  镜像 TS `z.number()` (允许小数, 与 ASS `FontSize` 一致)。
	 */
	fontSize?: number | null,
	/**
	 *  垂直边距(像素), 不填则自动: 竖屏 70 / 横屏 5
	 * 
	 *  镜像 TS `z.number().min(0)` (允许小数)。
	 */
	marginV?: number | null,
	/**  对齐位置; 默认 bottom-center */
	alignment?: Alignment | null,
	/**
	 *  描边宽度; 默认 0
	 * 
	 *  镜像 TS `z.number().min(0).default(0)` (允许小数)。
	 */
	outline?: number | null,
	/**
	 *  阴影宽度; 默认 1
	 * 
	 *  镜像 TS `z.number().min(0).default(1)` (允许小数)。
	 */
	shadow?: number | null,
	/**  ASS 字幕字体名 (须系统已安装), 默认 Noto Sans CJK SC */
	font?: string | null,
	/**  调试使用: 外部 srt 路径 */
	srtPath?: string | null,
	/**  调试使用: 外部 bgm 路径 */
	bgmPath?: string | null,
	/**  背景音乐增益(dB), 0=不变, 负值=衰减; 默认 -6 */
	bgmGain?: number | null,
	/**  配音增益(dB), 补偿合成语音偏小的听感差; 默认 3 */
	dubGain?: number | null,
	/**  是否启用本阶段 (缺省 true; 设为 false 可跳过 mix_video) */
	enabled?: boolean,
};

/**
 *  mix_video 阶段参数 (镜像 TS `packages/core/stages/mix_video/args.ts` MixVideoArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type MixVideoArgs_Serialize = {
	/**
	 *  字幕字号, 不填则自动: 竖屏 12(zh)/9(其他) ← 横屏 24(zh)/18(其他)
	 * 
	 *  镜像 TS `z.number()` (允许小数, 与 ASS `FontSize` 一致)。
	 */
	fontSize: number | null,
	/**
	 *  垂直边距(像素), 不填则自动: 竖屏 70 / 横屏 5
	 * 
	 *  镜像 TS `z.number().min(0)` (允许小数)。
	 */
	marginV: number | null,
	/**  对齐位置; 默认 bottom-center */
	alignment: Alignment | null,
	/**
	 *  描边宽度; 默认 0
	 * 
	 *  镜像 TS `z.number().min(0).default(0)` (允许小数)。
	 */
	outline: number | null,
	/**
	 *  阴影宽度; 默认 1
	 * 
	 *  镜像 TS `z.number().min(0).default(1)` (允许小数)。
	 */
	shadow: number | null,
	/**  ASS 字幕字体名 (须系统已安装), 默认 Noto Sans CJK SC */
	font: string | null,
	/**  调试使用: 外部 srt 路径 */
	srtPath: string | null,
	/**  调试使用: 外部 bgm 路径 */
	bgmPath: string | null,
	/**  背景音乐增益(dB), 0=不变, 负值=衰减; 默认 -6 */
	bgmGain: number | null,
	/**  配音增益(dB), 补偿合成语音偏小的听感差; 默认 3 */
	dubGain: number | null,
	/**  是否启用本阶段 (缺省 true; 设为 false 可跳过 mix_video) */
	enabled: boolean,
};

/**  OCR 运行设备。 */
export type OcrDevice = 
/**  cpu */
"cpu" | 
/**  cuda (NVIDIA) */
"cuda" | 
/**  directml (Windows) */
"directml" | 
/**  coreml (macOS) */
"coreml" | 
/**  rocm (AMD) */
"rocm" | 
/**  mps (Apple Silicon) */
"mps";

/**
 *  sf_ocr 阶段 OCR 修正参数。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type OcrFixArgs = OcrFixArgs_Serialize | OcrFixArgs_Deserialize;

/**
 *  sf_ocr 阶段 OCR 修正参数。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type OcrFixArgs_Deserialize = {
	/**  字幕段置信度阈值（0-1）：ocr-post filter-segment 用 adjusted_confidence_threshold 过滤，低于此值丢弃；默认 0.45 */
	adjustedConfidenceThreshold?: number | null,
	/**  单帧孤立惩罚的参考时间 (ms)，在此时长内无同文帧则视为完全孤立; 默认 1500 */
	isoThresholdMs?: number | null,
	/**  Y 偏移在调整置信度中的权重 (0~1); 默认 0.8 */
	adjustYWeight?: number | null,
	/**  孤立程度在调整置信度中的权重 (0~1); 默认 0.2 */
	adjustIsoWeight?: number | null,
	/**  Y 偏移惩罚归一化系数: 偏移量 / (videoHeight × adjustYFactor); 越小越严格; 默认 0.08 */
	adjustYFactor?: number | null,
	/**  box调整的置信度阈值: confidence < 此值则进行box调整; 默认 0.5 */
	boxAdjustedThreshold?: number | null,
	/**  是否合并子串 */
	isMergeSubstring?: boolean,
	/**  dedupOverlap 的编辑距离阈值: edit_distance ≤ 此值则合并; 默认 1 */
	dedupEditDistance?: number,
	/**  源语言代码 (供 LLM 系统提示, 镜像 TS `ctx.input.task.sourceLang`); 默认 "zh" */
	sourceLang?: string,
} & LlmFixArgs_Deserialize;

/**
 *  sf_ocr 阶段 OCR 修正参数。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type OcrFixArgs_Serialize = {
	/**  字幕段置信度阈值（0-1）：ocr-post filter-segment 用 adjusted_confidence_threshold 过滤，低于此值丢弃；默认 0.45 */
	adjustedConfidenceThreshold: number | null,
	/**  单帧孤立惩罚的参考时间 (ms)，在此时长内无同文帧则视为完全孤立; 默认 1500 */
	isoThresholdMs: number | null,
	/**  Y 偏移在调整置信度中的权重 (0~1); 默认 0.8 */
	adjustYWeight: number | null,
	/**  孤立程度在调整置信度中的权重 (0~1); 默认 0.2 */
	adjustIsoWeight: number | null,
	/**  Y 偏移惩罚归一化系数: 偏移量 / (videoHeight × adjustYFactor); 越小越严格; 默认 0.08 */
	adjustYFactor: number | null,
	/**  box调整的置信度阈值: confidence < 此值则进行box调整; 默认 0.5 */
	boxAdjustedThreshold: number | null,
	/**  是否合并子串 */
	isMergeSubstring: boolean,
	/**  dedupOverlap 的编辑距离阈值: edit_distance ≤ 此值则合并; 默认 1 */
	dedupEditDistance: number,
	/**  源语言代码 (供 LLM 系统提示, 镜像 TS `ctx.input.task.sourceLang`); 默认 "zh" */
	sourceLang: string,
} & LlmFixArgs_Serialize;

/**  OCR 推理运行时。 */
export type OcrRuntime = 
/**  ort-rust (opencv) */
"ort-rust";

export type OpProbes = OpProbes_Serialize | OpProbes_Deserialize;

export type OpProbes_Deserialize = {
	torch_conv1d?: ProbeResult | null,
};

export type OpProbes_Serialize = {
	torch_conv1d?: ProbeResult,
};

export type OrtBackend = {
	name: string,
	bundled: boolean,
};

export type OrtInfo = {
	version: string,
	backends: OrtBackend[],
};

/**  A single filesystem change delivered to a watcher. */
export type PathEvent = PathEvent_Serialize | PathEvent_Deserialize;

/**
 *  What happened to a watched path. Mirrors the subset of `notify::EventKind`
 *  we care about; `Rescan` is emitted when the OS watcher loses sync and the
 *  consumer should re-read state from disk rather than trust incremental events.
 */
export type PathEventKind = "Removed" | "Created" | "Changed" | "Rescan";

/**  A single filesystem change delivered to a watcher. */
export type PathEvent_Deserialize = {
	path: string,
	kind?: PathEventKind | null,
};

/**  A single filesystem change delivered to a watcher. */
export type PathEvent_Serialize = {
	path: string,
	kind: PathEventKind | null,
};

/**  任务模式: dub=配音, subtitle=仅字幕 */
export type Pipeline = "dub" | "subtitle";

export type PlatformInfo = PlatformInfo_Serialize | PlatformInfo_Deserialize;

export type PlatformInfo_Deserialize = {
	os: string,
	arch: string,
	release: string,
	hostname: string,
	runtime: string,
	runtimeVersion: string,
	nodeVersion?: string | null,
};

export type PlatformInfo_Serialize = {
	os: string,
	arch: string,
	release: string,
	hostname: string,
	runtime: string,
	runtimeVersion: string,
	nodeVersion?: string,
};

export type ProbeResult = "ok" | "fail";

/**  队列中的一条任务 */
export type QueueEntry = QueueEntry_Serialize | QueueEntry_Deserialize;

/**  队列中的一条任务 */
export type QueueEntry_Deserialize = {
	id: bigint,
	/**  完整任务配置 (input.task.action = start / continue, url/taskDir/continueFrom 在内) */
	input: Input_Deserialize,
	status: QueueStatus,
	error?: string | null,
};

/**  队列中的一条任务 */
export type QueueEntry_Serialize = {
	id: bigint,
	/**  完整任务配置 (input.task.action = start / continue, url/taskDir/continueFrom 在内) */
	input: Input_Serialize,
	status: QueueStatus,
	error: string | null,
};

/**  队列任务状态 */
export type QueueStatus = "Queued" | "Running" | "Done" | "Failed" | "Canceled";

/**
 *  An RPC error returned by any handler (query, mutate, subscribe).
 * 
 *  Maps to [`RpcError`](https://docs.rs/fnrpc-client/latest/fnrpc_client/class.RpcError.html)
 *  in the TypeScript client.
 * 
 *  # TS mirror
 * 
 *  ```typescript
 *  class RpcError extends Error {
 *    name: "RpcErr";
 *    code: string;
 *    message: string;
 *    data: unknown;
 *  }
 *  ```
 */
export type RpcErr = {
	name: string,
	code: string,
	message: string,
	data: unknown,
};

export type RunInfo = RunInfo_Serialize | RunInfo_Deserialize;

export type RunInfo_Deserialize = {
	asr?: AsrRunInfo_Deserialize | null,
};

export type RunInfo_Serialize = {
	asr: AsrRunInfo_Serialize | null,
};

/**
 *  separate 阶段参数 (镜像 TS `packages/core/stages/separate/args.ts` SeparateArgsSchema)
 * 
 *  枚举/数组默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})`), 这里只需处理
 *  「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 */
export type SeparateArgs = SeparateArgs_Serialize | SeparateArgs_Deserialize;

/**
 *  separate 阶段参数 (镜像 TS `packages/core/stages/separate/args.ts` SeparateArgsSchema)
 * 
 *  枚举/数组默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})`), 这里只需处理
 *  「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 */
export type SeparateArgs_Deserialize = {
	/**  推理运行时 */
	runtime?: SeparateRuntime,
	/**  torch:cuda (NVIDIA/ROCm), mps (Apple Silicon) */
	device?: Device,
	/**
	 *  效果(默认关闭): subtitle 模式下也始终分离人声, 保留 vocals 以便后续切换到 dub;
	 *  dub 流程下始终需要分离人声以保证 tts-vc 的质量
	 */
	always?: boolean,
	/**  需分离的 stems; 暂不被消费 */
	stems?: Stem[],
};

/**
 *  separate 阶段参数 (镜像 TS `packages/core/stages/separate/args.ts` SeparateArgsSchema)
 * 
 *  枚举/数组默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})`), 这里只需处理
 *  「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 */
export type SeparateArgs_Serialize = {
	/**  推理运行时 */
	runtime: SeparateRuntime,
	/**  torch:cuda (NVIDIA/ROCm), mps (Apple Silicon) */
	device: Device,
	/**
	 *  效果(默认关闭): subtitle 模式下也始终分离人声, 保留 vocals 以便后续切换到 dub;
	 *  dub 流程下始终需要分离人声以保证 tts-vc 的质量
	 */
	always: boolean,
	/**  需分离的 stems; 暂不被消费 */
	stems: Stem[],
};

/**
 *  separate 推理运行时
 * 
 *  TS 侧为 `z.enum(["burn", "burn-tch"])` (kebab-case), 故用 `rename_all = "kebab-case"`
 *  (`BurnTch` → `"burn-tch"`)。原先误用 `lowercase` 会得到 `"burntch"`, 与 TS 对不上,
 *  导致运行时 `"burn-tch"` 解析失败回落默认 (see `read_args_parses_camel_case_fields`)。
 */
export type SeparateRuntime = "burn" | "burn-tch";

/**
 *  服务器操作 (镜像 packages/core/servers/input.ts 的 action 枚举)
 *  (serde 与 clap 参数值统一为 lowercase)
 */
export type ServerAction = "status" | "start" | "stop" | "discovery";

export type ServerInfo = {
	host: string,
	port: number,
	found_via: FoundVia,
};

/**
 *  Server type identifiers for mDNS discovery.
 * 
 *  序列化为 snake_case (voxcpm_torch_gradio), 对齐 TS 侧
 *  `packages/config/src/servers.ts` 的 serverTypeList。
 *  (serde 与 clap 参数值统一为 snake_case)
 */
export type ServerType = 
/**  LocalDub 主服务器 (packages/server, fnrpc 端点, 端口 19110)。 */
"main" | "voxcpm_torch_gradio";

/**  servers 命令参数 (镜像 packages/core/servers/input.ts 的 ServersArgsSchema) */
export type ServersArgs = ServersArgs_Serialize | ServersArgs_Deserialize;

/**  servers 命令参数 (镜像 packages/core/servers/input.ts 的 ServersArgsSchema) */
export type ServersArgs_Deserialize = {
	/**  服务器操作 */
	action?: ServerAction,
	/**  指定操作的服务器, 不传则操作所有 */
	name?: ServerType | null,
	/**
	 *  start 前台模式: 继承终端 stdio (日志实时可见), Ctrl+C 直接终止;
	 *  默认 false = detach 后台 + 日志落盘 logs/server.log
	 */
	foreground?: boolean,
};

/**  servers 命令参数 (镜像 packages/core/servers/input.ts 的 ServersArgsSchema) */
export type ServersArgs_Serialize = {
	/**  服务器操作 */
	action: ServerAction,
	/**  指定操作的服务器, 不传则操作所有 */
	name: ServerType | null,
	/**
	 *  start 前台模式: 继承终端 stdio (日志实时可见), Ctrl+C 直接终止;
	 *  默认 false = detach 后台 + 日志落盘 logs/server.log
	 */
	foreground: boolean,
};

/**
 *  sf_ocr 阶段参数。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type SfOcrArgs = SfOcrArgs_Serialize | SfOcrArgs_Deserialize;

/**
 *  sf_ocr 阶段参数。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type SfOcrArgs_Deserialize = {
	/**  OCR 推理运行时: ort-rust (opencv) */
	runtime?: OcrRuntime,
	/**  OCR 运行设备: cpu, cuda, directml, coreml, rocm, mps */
	device?: OcrDevice,
	/**  OCR 识别置信度阈值, 默认 0.45 */
	textConfidenceThreshold?: number | null,
	/**  只识别字幕区域 (Y轴裁剪); 默认 true */
	subtitleOnly?: boolean,
	/**  步骤完成后是否删除抽出的帧图片; 默认 false (保留) */
	cleanupFrames?: boolean,
};

/**
 *  sf_ocr 阶段参数。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故这里手写 `impl Default`
 *  以保证两种路径下默认值一致 (与 `input::stages::Asr` 同款处理)。
 */
export type SfOcrArgs_Serialize = {
	/**  OCR 推理运行时: ort-rust (opencv) */
	runtime: OcrRuntime,
	/**  OCR 运行设备: cpu, cuda, directml, coreml, rocm, mps */
	device: OcrDevice,
	/**  OCR 识别置信度阈值, 默认 0.45 */
	textConfidenceThreshold: number | null,
	/**  只识别字幕区域 (Y轴裁剪); 默认 true */
	subtitleOnly: boolean,
	/**  步骤完成后是否删除抽出的帧图片; 默认 false (保留) */
	cleanupFrames: boolean,
};

/**  侧链压缩器参数 (镜像 TS `sidechainCompress`) */
export type SidechainCompress = SidechainCompress_Serialize | SidechainCompress_Deserialize;

/**  侧链压缩器参数 (镜像 TS `sidechainCompress`) */
export type SidechainCompress_Deserialize = {
	/**  压缩器阈值, 默认 0.1 */
	threshold?: number | null,
	/**  压缩比, 默认 20 */
	ratio?: number | null,
	/**  attack 时间(ms), 默认 1 */
	attack?: number | null,
	/**  release 时间(ms), 默认 200 */
	release?: number | null,
};

/**  侧链压缩器参数 (镜像 TS `sidechainCompress`) */
export type SidechainCompress_Serialize = {
	/**  压缩器阈值, 默认 0.1 */
	threshold: number | null,
	/**  压缩比, 默认 20 */
	ratio: number | null,
	/**  attack 时间(ms), 默认 1 */
	attack: number | null,
	/**  release 时间(ms), 默认 200 */
	release: number | null,
};

/**
 *  split_audio 阶段参数 (镜像 TS `packages/core/stages/06_split_audio/args.ts` SplitAudioArgsSchema)
 * 
 *  默认值带业务含义 (startPadMs=100 / endPadMs=300)。TS 端 zod `.prefault({})`
 *  在写入 ctx.json 前已落定默认值, 因此这里只需处理「对象存在但字段缺」:
 *  用 `#[serde(default = "…")]` 兜底。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故手写 `impl Default`
 *  以保证两种路径下默认值一致 (vadAlign=false / startPadMs=100 / endPadMs=300)。
 */
export type SplitAudioArgs = SplitAudioArgs_Serialize | SplitAudioArgs_Deserialize;

/**
 *  split_audio 阶段参数 (镜像 TS `packages/core/stages/06_split_audio/args.ts` SplitAudioArgsSchema)
 * 
 *  默认值带业务含义 (startPadMs=100 / endPadMs=300)。TS 端 zod `.prefault({})`
 *  在写入 ctx.json 前已落定默认值, 因此这里只需处理「对象存在但字段缺」:
 *  用 `#[serde(default = "…")]` 兜底。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故手写 `impl Default`
 *  以保证两种路径下默认值一致 (vadAlign=false / startPadMs=100 / endPadMs=300)。
 */
export type SplitAudioArgs_Deserialize = {
	/**  是否启用静音检测对齐: 修正 segments 前后静音导致的偏移 */
	vadAlign?: boolean,
	/**  段落切块前缘 padding (ms), 避免语音被截断 */
	startPadMs?: bigint,
	/**  段落切块后缘 padding (ms), 避免语音被截断 */
	endPadMs?: bigint,
	/**  人声文件路径, 调试使用 */
	vocalsFilePath?: string | null,
	/**  原始视频音频路径, 调试使用 */
	sourceFilePath?: string | null,
};

/**
 *  split_audio 阶段参数 (镜像 TS `packages/core/stages/06_split_audio/args.ts` SplitAudioArgsSchema)
 * 
 *  默认值带业务含义 (startPadMs=100 / endPadMs=300)。TS 端 zod `.prefault({})`
 *  在写入 ctx.json 前已落定默认值, 因此这里只需处理「对象存在但字段缺」:
 *  用 `#[serde(default = "…")]` 兜底。
 * 
 *  注意: `#[serde(default = "fn")]` 仅在字段级反序列化时生效; 当父结构用
 *  `#[serde(default)]` 整体缺省时会调用 Rust `Default`, 故手写 `impl Default`
 *  以保证两种路径下默认值一致 (vadAlign=false / startPadMs=100 / endPadMs=300)。
 */
export type SplitAudioArgs_Serialize = {
	/**  是否启用静音检测对齐: 修正 segments 前后静音导致的偏移 */
	vadAlign: boolean,
	/**  段落切块前缘 padding (ms), 避免语音被截断 */
	startPadMs: bigint,
	/**  段落切块后缘 padding (ms), 避免语音被截断 */
	endPadMs: bigint,
	/**  人声文件路径, 调试使用 */
	vocalsFilePath: string | null,
	/**  原始视频音频路径, 调试使用 */
	sourceFilePath: string | null,
};

/**  pipeline 阶段名 (stagesList) */
export type StageName = "separate" | "separate_after" | "asr" | "asr_fix" | "sf_ocr_pre" | "sf_ocr" | "sf_ocr_fix" | "asr_ocr_pre" | "asr_ocr" | "asr_ocr_fix" | "translate" | "split_audio" | "tts" | "mix_audio" | "mix_video";

export type StageStatus = "pending" | "running" | "success" | "failed";

/**
 *  各处理阶段的入参 (镜像 TS `packages/core/input/types.ts` StagesSchema)
 * 
 *  mix_audio / mix_video 直接使用 `crate::stages::{mix_audio,mix_video}::args` 的
 *  完整定义，与 TS `MixAudioArgsSchema` / `MixVideoArgsSchema` 对齐。
 *  sf_ocr / asr_ocr 系列同样复用各自 stage 目录下的 args 定义。
 */
export type Stages = Stages_Serialize | Stages_Deserialize;

/**
 *  各处理阶段的入参 (镜像 TS `packages/core/input/types.ts` StagesSchema)
 * 
 *  mix_audio / mix_video 直接使用 `crate::stages::{mix_audio,mix_video}::args` 的
 *  完整定义，与 TS `MixAudioArgsSchema` / `MixVideoArgsSchema` 对齐。
 *  sf_ocr / asr_ocr 系列同样复用各自 stage 目录下的 args 定义。
 */
export type Stages_Deserialize = {
	separate?: SeparateArgs_Deserialize,
	asr?: AsrArgs_Deserialize,
	asr_fix?: AsrFixArgs_Deserialize,
	sf_ocr?: SfOcrArgs_Deserialize,
	sf_ocr_fix?: OcrFixArgs_Deserialize,
	asr_ocr_pre?: AsrOcrPreArgs_Deserialize,
	asr_ocr?: AsrOcrArgs_Deserialize,
	asr_ocr_fix?: AsrOcrFixArgs_Deserialize,
	translate?: TranslateArgs_Deserialize,
	split_audio?: SplitAudioArgs_Deserialize,
	tts?: TtsArgs_Deserialize,
	mix_audio?: MixAudioArgs_Deserialize,
	mix_video?: MixVideoArgs_Deserialize,
};

/**
 *  各处理阶段的入参 (镜像 TS `packages/core/input/types.ts` StagesSchema)
 * 
 *  mix_audio / mix_video 直接使用 `crate::stages::{mix_audio,mix_video}::args` 的
 *  完整定义，与 TS `MixAudioArgsSchema` / `MixVideoArgsSchema` 对齐。
 *  sf_ocr / asr_ocr 系列同样复用各自 stage 目录下的 args 定义。
 */
export type Stages_Serialize = {
	separate: SeparateArgs_Serialize,
	asr: AsrArgs_Serialize,
	asr_fix: AsrFixArgs_Serialize,
	sf_ocr: SfOcrArgs_Serialize,
	sf_ocr_fix: OcrFixArgs_Serialize,
	asr_ocr_pre: AsrOcrPreArgs_Serialize,
	asr_ocr: AsrOcrArgs_Serialize,
	asr_ocr_fix: AsrOcrFixArgs_Serialize,
	translate: TranslateArgs_Serialize,
	split_audio: SplitAudioArgs_Serialize,
	tts: TtsArgs_Serialize,
	mix_audio: MixAudioArgs_Serialize,
	mix_video: MixVideoArgs_Serialize,
};

/**  可分离的 stem */
export type Stem = "drums" | "bass" | "other" | "vocals";

/**  字幕源 */
export type SubtitleSource = "asr" | "sf_ocr" | "asr_ocr";

/**  目标语言 (langList) */
export type TargetLang = "en" | "zh" | "vi" | "ja" | "ko" | "fr" | "de" | "es" | "pt" | "ru" | "ar" | "hi" | "th" | "id" | "ms" | "tl" | "my" | "km" | "lo" | "mn" | "ne" | "ur" | "bn";

export type Task = Task_Serialize | Task_Deserialize;

/**  任务操作 (serde 与 clap 参数值统一为 snake_case) */
export type TaskAction = "start" | "continue" | "enqueue_start" | "enqueue_continue" | "list_queue" | "cancel_queue" | "status" | "get_group_list" | "get_task_ctx" | "generate_meta";

/**  任务参数 (镜像 taskArgsSchema) */
export type TaskArgs = TaskArgs_Serialize | TaskArgs_Deserialize;

/**  任务参数 (镜像 taskArgsSchema) */
export type TaskArgs_Deserialize = {
	/**  任务操作: start=开始, continue=继续, status=显示状态, get_group_list=列出分组 */
	action?: TaskAction | null,
	/**  本地文件路径或云端文件 url、youtubeUrl、bilibiliUrl */
	url?: string | null,
	sourceLang?: TargetLang | null,
	targetLang?: TargetLang | null,
	/**  继续任务专业参数, 可指定 continueFrom 从某步骤开始, 不指定则从上次中断的步骤开始 */
	continueFrom?: StageName | null,
	/**  目标步骤, pipeline 跑到此步骤后自动停止, 不指定则跑完所有步骤 */
	targetStage?: StageName | null,
	taskDir?: string | null,
	/**  队列任务 ID (cancel_queue 指定要取消的队列项) */
	queueId?: bigint | null,
	/**  rerunStage 专业参数, 指定要重新运行的步骤 */
	stageName?: StageName | null,
	/**  任务模式, dub 配音, subtitle 仅字幕 */
	pipeline?: Pipeline,
	/**  字幕源: asr (whisper, 默认), sf_ocr (关键帧策略硬字幕提取), asr_ocr (ASR 时序+OCR 文本融合) */
	subtitleSource?: SubtitleSource,
	/**
	 *  是否下载平台自带字幕 (YouTube/Bilibili 的官方/自动字幕)。
	 *  注意: YouTube 现要求 PO token, 无 bgutil 服务时下载会失败 (best-effort, 不阻断主流程)。
	 */
	downloadSubtitles?: boolean,
};

/**  任务参数 (镜像 taskArgsSchema) */
export type TaskArgs_Serialize = {
	/**  任务操作: start=开始, continue=继续, status=显示状态, get_group_list=列出分组 */
	action: TaskAction | null,
	/**  本地文件路径或云端文件 url、youtubeUrl、bilibiliUrl */
	url: string | null,
	sourceLang: TargetLang | null,
	targetLang: TargetLang | null,
	/**  继续任务专业参数, 可指定 continueFrom 从某步骤开始, 不指定则从上次中断的步骤开始 */
	continueFrom: StageName | null,
	/**  目标步骤, pipeline 跑到此步骤后自动停止, 不指定则跑完所有步骤 */
	targetStage: StageName | null,
	taskDir: string | null,
	/**  队列任务 ID (cancel_queue 指定要取消的队列项) */
	queueId: bigint | null,
	/**  rerunStage 专业参数, 指定要重新运行的步骤 */
	stageName: StageName | null,
	/**  任务模式, dub 配音, subtitle 仅字幕 */
	pipeline: Pipeline,
	/**  字幕源: asr (whisper, 默认), sf_ocr (关键帧策略硬字幕提取), asr_ocr (ASR 时序+OCR 文本融合) */
	subtitleSource: SubtitleSource,
	/**
	 *  是否下载平台自带字幕 (YouTube/Bilibili 的官方/自动字幕)。
	 *  注意: YouTube 现要求 PO token, 无 bgutil 服务时下载会失败 (best-effort, 不阻断主流程)。
	 */
	downloadSubtitles: boolean,
};

export type TaskBrief = TaskBrief_Serialize | TaskBrief_Deserialize;

export type TaskBrief_Deserialize = {
	id: string,
	title?: string | null,
	status: string,
	current_stage?: string | null,
	created_at: string,
	started_at?: string | null,
	completed_at?: string | null,
	error_message?: string | null,
};

export type TaskBrief_Serialize = {
	id: string,
	title: string | null,
	status: string,
	current_stage: string | null,
	created_at: string,
	started_at: string | null,
	completed_at: string | null,
	error_message: string | null,
};

export type TaskCtx = TaskCtx_Serialize | TaskCtx_Deserialize;

export type TaskCtx_Deserialize = {
	task: Task_Deserialize,
	stages?: TaskStage_Deserialize[] | null,
	pipeline: string,
	last_run_pipeline?: string | null,
	input: unknown,
	frame_rate: FrameRate,
	run_info?: RunInfo_Deserialize | null,
	video_source_path?: string | null,
	audio_source_path?: string | null,
	asr_language?: string | null,
	target_language?: string | null,
};

export type TaskCtx_Serialize = {
	task: Task_Serialize,
	stages: TaskStage_Serialize[] | null,
	pipeline: string,
	last_run_pipeline: string | null,
	input: unknown,
	frame_rate: FrameRate,
	run_info: RunInfo_Serialize | null,
	video_source_path: string | null,
	audio_source_path: string | null,
	asr_language: string | null,
	target_language: string | null,
};

export type TaskStage = TaskStage_Serialize | TaskStage_Deserialize;

export type TaskStage_Deserialize = {
	name: string,
	label: string,
	status?: StageStatus,
	progress?: number | null,
	started_at?: string | null,
	completed_at?: string | null,
	last_message?: string | null,
	error_message?: string | null,
};

export type TaskStage_Serialize = {
	name: string,
	label: string,
	status: StageStatus,
	progress: number | null,
	started_at: string | null,
	completed_at: string | null,
	last_message: string | null,
	error_message: string | null,
};

export type Task_Deserialize = {
	id: string,
	source: VideoSource,
	url: string,
	title?: string | null,
	status: string,
	current_stage?: string | null,
	task_dir: string,
	final_video_path?: string | null,
	error_message?: string | null,
	created_at: string,
	started_at?: string | null,
	completed_at?: string | null,
};

export type Task_Serialize = {
	id: string,
	source: VideoSource,
	url: string,
	title: string | null,
	status: string,
	current_stage: string | null,
	task_dir: string,
	final_video_path: string | null,
	error_message: string | null,
	created_at: string,
	started_at: string | null,
	completed_at: string | null,
};

/**
 *  translate 阶段参数 (镜像 TS `packages/core/stages/05_translate/args.ts` TranslateArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 */
export type TranslateArgs = TranslateArgs_Serialize | TranslateArgs_Deserialize;

/**
 *  translate 阶段参数 (镜像 TS `packages/core/stages/05_translate/args.ts` TranslateArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 */
export type TranslateArgs_Deserialize = {
	/**  OpenAI 兼容端点 */
	apiBase?: string,
	/**  翻译模型 */
	model?: string,
	/**  目标语言; 不填则按逻辑: 源语言 zh -> en, 否则 any -> zh */
	targetLang?: TargetLang | null,
	/**  设为 false 跳过翻译, 直接使用原始识别文本 */
	enabled?: boolean,
};

/**
 *  translate 阶段参数 (镜像 TS `packages/core/stages/05_translate/args.ts` TranslateArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 */
export type TranslateArgs_Serialize = {
	/**  OpenAI 兼容端点 */
	apiBase: string,
	/**  翻译模型 */
	model: string,
	/**  目标语言; 不填则按逻辑: 源语言 zh -> en, 否则 any -> zh */
	targetLang: TargetLang | null,
	/**  设为 false 跳过翻译, 直接使用原始识别文本 */
	enabled: boolean,
};

/**
 *  tts 阶段参数 (镜像 TS `packages/core/stages/07_tts/args.ts` TtsStageArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 */
export type TtsArgs = TtsArgs_Serialize | TtsArgs_Deserialize;

/**
 *  tts 阶段参数 (镜像 TS `packages/core/stages/07_tts/args.ts` TtsStageArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 */
export type TtsArgs_Deserialize = {
	/**  运行时后端; 默认 cloud */
	runtime?: TtsRuntime,
	/**  计算设备; 默认 cuda */
	device?: TtsDevice,
	/**  跳过已存在的段 (按 mtime 比对参考音); 默认 true */
	skipExisting?: boolean,
	/**
	 *  continue 模式下强制重新生成的 segment 索引 (1-based); 列表外段保留旧结果。
	 *  命中段无视 skipExisting, 强制重合成 (先删旧 wav 再生成)。None/空 = 全量按 skipExisting 走。
	 */
	regenIndices?: number[] | null,
	/**  将短参考音频 (< 2500ms) 拼接一倍再送 TTS, 帮助稳定输出音色; 默认 false */
	refAudioX2?: boolean,
};

/**
 *  tts 阶段参数 (镜像 TS `packages/core/stages/07_tts/args.ts` TtsStageArgsSchema)
 * 
 *  枚举/字符串默认值 TS 在写入 ctx.json 前已落定 (zod `.prefault({})` / `.default(...)`),
 *  这里只需处理「对象存在但字段缺」: 字段级 `#[serde(default…)]` 兜底即可。
 */
export type TtsArgs_Serialize = {
	/**  运行时后端; 默认 cloud */
	runtime: TtsRuntime,
	/**  计算设备; 默认 cuda */
	device: TtsDevice,
	/**  跳过已存在的段 (按 mtime 比对参考音); 默认 true */
	skipExisting: boolean,
	/**
	 *  continue 模式下强制重新生成的 segment 索引 (1-based); 列表外段保留旧结果。
	 *  命中段无视 skipExisting, 强制重合成 (先删旧 wav 再生成)。None/空 = 全量按 skipExisting 走。
	 */
	regenIndices: number[] | null,
	/**  将短参考音频 (< 2500ms) 拼接一倍再送 TTS, 帮助稳定输出音色; 默认 false */
	refAudioX2: boolean,
};

/**  TTS 计算设备 (镜像 TS `packages/core/stages/07_tts/args.ts` TtsStageArgsSchema.device) */
export type TtsDevice = "webgpu" | "cuda" | "rocm" | "cpu" | "mps";

/**  TTS 运行时后端 (镜像 TS `packages/core/stages/07_tts/args.ts` TtsStageArgsSchema.runtime) */
export type TtsRuntime = "ggml" | "cloud" | "voxcpmtorchgradio";

/**  whisper.cpp VAD 模型 */
export type VadModel = "silero-v5" | "silero-v6";

export type Value = null | boolean | number | string | Value[] | { [key in string]: Value };

export type Vendor = "amd" | "nvidia" | "intel" | "unknown";

export type VideoSource = "youtube" | "bilibili" | "local" | "remote" | "unknown";

export type VramInfo = VramInfo_Serialize | VramInfo_Deserialize;

export type VramInfo_Deserialize = {
	percent: number | null,
	total?: number | null,
	used?: number | null,
	type?: VramType | null,
	reserved?: number | null,
	gtt?: number | null,
};

export type VramInfo_Serialize = {
	percent: number | null,
	total?: number | null,
	used?: number | null,
	type?: VramType,
	reserved?: number | null,
	gtt?: number | null,
};

export type VramType = "dedicated" | "shared" | "unknown";

export type VulkanHeaps = {
	deviceLocal: number | null,
	hostVisible: number | null,
};

export type Procedures = {
  read_app_file_text: { kind: "query"; method: "GET"; input: string; output: string; error: RpcErr };
  write_app_file_text: { kind: "mutate"; method: "POST"; input: [string, string]; output: null; error: RpcErr };
  read_app_file_json: { kind: "query"; method: "GET"; input: string; output: Value; error: RpcErr };
  write_app_file_json: { kind: "mutate"; method: "POST"; input: [string, Value]; output: null; error: RpcErr };
  read_app_file_bin: { kind: "query"; method: "GET"; input: string; output: number[]; error: RpcErr };
  list_app_directory: { kind: "query"; method: "GET"; input: string; output: DirEntry[]; error: RpcErr };
  watch_task_log: { kind: "subscribe"; method: "GET"; input: string; output: string; error: RpcErr };
  watch_task_tree: { kind: "subscribe"; method: "GET"; input: string; output: PathEvent; error: RpcErr };
  tick: { kind: "subscribe"; method: "GET"; input: bigint; output: bigint; error: RpcErr };
  get_group_list: { kind: "query"; method: "GET"; input: null; output: GroupInfo[]; error: RpcErr };
  get_task_ctx: { kind: "query"; method: "GET"; input: string; output: TaskCtx; error: RpcErr };
  health_check: { kind: "query"; method: "GET"; input: null; output: string; error: RpcErr };
  get_count: { kind: "query"; method: "GET"; input: null; output: string; error: RpcErr };
  reset_count: { kind: "mutate"; method: "POST"; input: null; output: null; error: RpcErr };
  find_server: { kind: "query"; method: "GET"; input: ServerType; output: ServerInfo; error: RpcErr };
  start_torch: { kind: "mutate"; method: "POST"; input: null; output: number; error: RpcErr };
  stop_torch: { kind: "mutate"; method: "POST"; input: null; output: null; error: RpcErr };
  check_torch: { kind: "query"; method: "GET"; input: null; output: boolean; error: RpcErr };
  start_voxcpm: { kind: "mutate"; method: "POST"; input: null; output: number; error: RpcErr };
  stop_voxcpm: { kind: "mutate"; method: "POST"; input: null; output: null; error: RpcErr };
  shutdown: { kind: "mutate"; method: "POST"; input: null; output: string; error: RpcErr };
  device_info: { kind: "query"; method: "GET"; input: null; output: DeviceInfo; error: RpcErr };
  get_workfolder: { kind: "query"; method: "GET"; input: null; output: string; error: RpcErr };
  continue_task: { kind: "mutate"; method: "POST"; input: [string, string]; output: null; error: RpcErr };
  regen_tts: { kind: "mutate"; method: "POST"; input: [string, number[], boolean]; output: null; error: RpcErr };
  start_task: { kind: "mutate"; method: "POST"; input: string; output: string; error: RpcErr };
  enqueue_start: { kind: "mutate"; method: "POST"; input: Input; output: bigint; error: RpcErr };
  enqueue_continue: { kind: "mutate"; method: "POST"; input: Input; output: bigint; error: RpcErr };
  list_queue: { kind: "query"; method: "GET"; input: null; output: QueueEntry[]; error: RpcErr };
  cancel_queue: { kind: "mutate"; method: "POST"; input: bigint; output: boolean; error: RpcErr };
}

export const __procedureMeta = {
  read_app_file_text: { kind: "query", method: "GET" },
  write_app_file_text: { kind: "mutate", method: "POST" },
  read_app_file_json: { kind: "query", method: "GET" },
  write_app_file_json: { kind: "mutate", method: "POST" },
  read_app_file_bin: { kind: "query", method: "GET" },
  list_app_directory: { kind: "query", method: "GET" },
  watch_task_log: { kind: "subscribe", method: "GET" },
  watch_task_tree: { kind: "subscribe", method: "GET" },
  tick: { kind: "subscribe", method: "GET" },
  get_group_list: { kind: "query", method: "GET" },
  get_task_ctx: { kind: "query", method: "GET" },
  health_check: { kind: "query", method: "GET" },
  get_count: { kind: "query", method: "GET" },
  reset_count: { kind: "mutate", method: "POST" },
  find_server: { kind: "query", method: "GET" },
  start_torch: { kind: "mutate", method: "POST" },
  stop_torch: { kind: "mutate", method: "POST" },
  check_torch: { kind: "query", method: "GET" },
  start_voxcpm: { kind: "mutate", method: "POST" },
  stop_voxcpm: { kind: "mutate", method: "POST" },
  shutdown: { kind: "mutate", method: "POST" },
  device_info: { kind: "query", method: "GET" },
  get_workfolder: { kind: "query", method: "GET" },
  continue_task: { kind: "mutate", method: "POST" },
  regen_tts: { kind: "mutate", method: "POST" },
  start_task: { kind: "mutate", method: "POST" },
  enqueue_start: { kind: "mutate", method: "POST" },
  enqueue_continue: { kind: "mutate", method: "POST" },
  list_queue: { kind: "query", method: "GET" },
  cancel_queue: { kind: "mutate", method: "POST" },
} as const;
